language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r springboot2-aws
  - mkdir -p deploy
  - mv springboot2-aws.zip deploy/springboot2-aws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot2-awsbuild
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - vitriol95@naver.com